### ISSUE TITLE
Obtaining a Long-Term Valid Login Command

### ISSUE THREAD

**Issue by znkovacs** [opentelekomcloud-docs/software-repository-container#27]
Issue on page:        https://github.com/opentelekomcloud-docs/software-repository-container/blob/main/umn/source/image_management/obtaining_a_long-term_valid_login_command.rst

Under chapter "4. Put the information you obtained..." there is a screenshot that contains huawei domains instead of otc.

**Comment by oeotvos** [comment]
Thank you for your remark. The issue will be resolved soon.
(int#CONT-1340)

**Comment by oeotvos** [comment]
Thank you for the notice. Corrected. https://docs.otc.t-systems.com/software-repository-container/umn/image_management/obtaining_a_long-term_valid_login_command.html#
