### ISSUE TITLE
Obtaining a Long-Term Valid Login Command

### ISSUE THREAD

**Issue by uli-schneider** [opentelekomcloud-docs/software-repository-container#41]
Issue on page:        https://github.com/opentelekomcloud-docs/software-repository-container/blob/main/umn/source/image_management/obtaining_a_long-term_valid_login_command.rst

Image in Figure-2 shows "myhuaweicloud.com" 

Please replace with a valid screen shot for Open Telekom Cloud

**Comment by oeotvos** [comment]
Thank you for the notice. Corrected. https://docs.otc.t-systems.com/software-repository-container/umn/image_management/obtaining_a_long-term_valid_login_command.html#
