### ISSUE TITLE
Obtaining a Long-Term Valid Login Command

### ISSUE THREAD

**Issue by canaykin** [opentelekomcloud-docs/software-repository-container#42]
Issue on page:        https://github.com/opentelekomcloud-docs/software-repository-container/blob/main/umn/source/image_management/obtaining_a_long-term_valid_login_command.rst

Figure 2 depicting the docker login command shows the swr address under domain myhuaweicloud.com

**Comment by oeotvos** [comment]
Thank you for the notice. Corrected. https://docs.otc.t-systems.com/software-repository-container/umn/image_management/obtaining_a_long-term_valid_login_command.html#
